CREATE TABLE "ONEPFP"."ACTIVE" 
   (	"USER_ID" VARCHAR2(32), 
	"IMAGE_ID" VARCHAR2(200), 
	"SESSION_ID" VARCHAR2(32), 
	 CONSTRAINT "ACTIVE_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "ACTIVE_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "ONEPFP"."USERS" ("USER_ID") ENABLE, 
	 CONSTRAINT "ACTIVE_FK2" FOREIGN KEY ("SESSION_ID")
	  REFERENCES "ONEPFP"."SESSIONS" ("SESSION_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS";
