CREATE TABLE "ONEPFP"."IMAGES" 
   (	"IMAGE_ID" VARCHAR2(200), 
	"USER_ID" VARCHAR2(32) NOT NULL ENABLE, 
	"SESSION_ID" VARCHAR2(32) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(10), 
	 CONSTRAINT "PK_IMAGES" PRIMARY KEY ("USER_ID", "SESSION_ID", "IMAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_IMAGES_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "ONEPFP"."USERS" ("USER_ID") ENABLE, 
	 CONSTRAINT "FK_IMAGES_SESSION" FOREIGN KEY ("SESSION_ID", "USER_ID")
	  REFERENCES "ONEPFP"."SESSIONS" ("SESSION_ID", "USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
